ROM debian:stretch

RUN apt update
RUN apt install -y git \
                   build-essential \
                   ssh \
                   vim \
                   tmux \
                   python3 \
                   python3-pip \
                   python3-venv \
                   python3-dev \

RUN apt install -y iverilog \
                   gtkwave

RUN git clone https://github.com/cocotb/cocotb.git cocotb
RUN python3 -m pip install ./cocotb
RUN make -C cocotb/examples/endian_swapper/tests

# Icestorm project dependencies
RUN apt install -y build-essential clang bison flex libreadline-dev \
                   gawk tcl-dev libffi-dev git mercurial graphviz   \
                   xdot pkg-config python python3 libftdi-dev \
                   qt5-default python3-dev libboost-all-dev cmake

RUN git clone https://github.com/cliffordwolf/icestorm.git icestorm
RUN make -C icestorm -j$(nproc) && make -C icestorm install

RUN git clone https://github.com/cseed/arachne-pnr.git arachne-pnr
RUN make -C arachne-pnr -j$(nproc) && make -C arachne-pnr install

# Dependencies:
RUN apt install -y libeigen3-dev
RUN git clone https://github.com/YosysHQ/nextpnr nextpnr
RUN cd nextpnr
RUN cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local .
RUN make -j$(nproc) && make install
RUN cd ..

RUN git clone https://github.com/cliffordwolf/yosys.git yosys
RUN make -C yosys -j$(nproc) && make -C yosys install

RUN echo ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6010", MODE="0660", GROUP="plugdev", TAG+="uaccess" >> /etc/udev/rules.d/53-lattice-ftdi.rules



ENV COCOTB /cocotb/





#COPY . /app
#RUN make /app
#CMD python /app/app.py

ENTRYPOINT ["/bin/bash"]
#CMD ["-las"]
